Publish builds and toolchains to repo.saltproject.io
saltstack/relative-environment-for-python pull request #133
Opened 2023-06-20 19:02 UTC by MKLeb

2023-06-20 19:18 UTC, MKLeb commented
https://github.com/MKLeb/relative-environment-for-python/actions/runs/5326011082
Example test release

2023-06-20 21:10 UTC, MKLeb commented
@dwoz , this isn't necessarily a code change, but I'm wondering if this might need a changelog?

2023-06-21 10:01 UTC, s0undt3ch requested changes
This is the commit to revert?

2023-06-21 13:50 UTC, s0undt3ch approved these changes

2023-07-13 21:28 UTC, merged