Add native arm64 builds
saltstack/relative-environment-for-python pull request #32
Opened 2022-11-10 17:14 UTC by MKLeb

2022-11-16 02:14 UTC, s0undt3ch approved these changes

2022-11-16 21:53 UTC, dwoz requested changes

2022-11-16 21:53 UTC, dwoz commented on .github/workflows/build-action.yml
> +        exclude:
We don't need this

2022-11-16 21:53 UTC, dwoz commented on .github/workflows/build-action.yml
> +          name: ${{ matrix.host }}-${{ matrix.target }}-linux-gnu.tar.xz
Changing the name of the artifacts will cause release builds to fail. Since we're not adding any artifacts let's keep the name the same.

2022-11-17 20:53 UTC, dwoz approved these changes

2022-11-17 21:01 UTC, MKLeb commented
I approve this after the revisions made by @dwoz.

2022-11-17 21:14 UTC, merged